### ISSUE TITLE
Simplify room's name

### ISSUE THREAD

**Issue by lebaudantoine** [numerique-gouv/meet#41]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
The current use of UUID-v4 as room IDs is suboptimal for user experience (UX). These IDs are long and complex, making them cumbersome for users to share in room URLs. ex: 

`https://meet.numerique.gouv.fr/bc54fd45-bffe-4ffa-8797-6d0499b43f56`

**Examples from other platforms:**
- **Google Meet** uses a shorter, user-friendly format for room IDs, such as `raq-rsqx-mjh`, which follows a `xxx-xxxx-xxx` pattern where `x` represents random characters, including letters.
- **LiveKit** uses a similar approach with room IDs like `yyyy-yyyy`, where `y` represents random characters, including letters and numbers.
- **Jitsi** [documentation](https://jitsi.org/security/) suggests avoiding long and uninviting UUIDs in favor of custom, yet sufficiently long, names to prevent collisions.

> If you don’t like the funky way the auto-generated names sound and you don’t want to use a long and uninviting [UUID](https://www.uuidgenerator.net/) (which you totally could), then go ahead ...

UUID-v4 room IDs are long and uninviting. Shorter, custom room IDs can enhance UX by making URLs easier to share and remember.

**Collision Considerations:**
- Google Meet's format results in 26^10 = 1.411671e+14 possible combinations.
- The collision odds for any two UUID-v4s are 1 in 2.71e+18.
  
While UUID-v4s are typically used in database systems for their low collision probability, for ephemeral room IDs, the collision risk of e+14 combinations is acceptable. Additionally, once a meeting ends, its ID can be reused, further reducing collision concerns.

___ 
**Describe the solution you'd like**
Implement a custom function in the frontend to generate room IDs similar to Google Meet's naming convention.

___ 
**Describe alternatives you've considered**
Keeping the current UUID-v4 format.

___ 
**Discovery, Documentation, Adoption, Migration Strategy**
LiveKit Example:
```javascript
export function generateRoomId(): string {
  return `${randomString(4)}-${randomString(4)}`;
}

export function randomString(length: number): string {
  let result = '';
  const characters = 'abcdefghijklmnopqrstuvwxyz0123456789';
  const charactersLength = characters.length;
  for (let i = 0; length > i; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }
  return result;
}
```
[source](https://github.com/livekit-examples/meet/blob/main/lib/client-utils.ts#L31)

**Comment by lebaudantoine** [comment]
We should validate that the URL queried respect the ID format

**Comment by CamCaz1** [comment]
Not much to say except “Duuuuh” 😉 [already in 2017 there were articles about it](https://uxdesign.cc/its-time-for-cleaner-shorter-urls-to-rule-the-web-96c023f6b8ee). So all the way. On the other hand, let's see the priority level of the ticket according to reality today: what is the average length of the url generated with livekit? + or - painful depending on the answer.

**Comment by manuhabitela** [comment]
My ideal pov on room names is that we should be able to direct them via URL and name them how we want.

Like I could automatically create a room, if I'm logged in, by going on https://meet.numerique.gouv.fr/my-custom-room-name. If it already exists, I join it.

To prevent the issue of "someone I don't know joined my room with an easy-to-guess name" (because now it's more of a problem than with random ids), we can:

- on creation, have rules to prevent too easily guessable names (like a required minimum length),
- make a room have a waiting room by default, something the room creator could change easily

This is kinda what https://meet.jit.si/ does.

It makes it pretty easy to handle a "regular room" feature. Everybody knows to just go back to https://meet.numerique.gouv.fr/my-daily-meeting-room-name everyday. The browser address bar history suggestions are instantly recognizable. On the room page, this can maybe also lead to us setting up a page `<title>` automatically from the URL (`My daily meeting room name`), also making it easier to find in browser history.

I realize it has its downsides and that creates a bit more work than random ids but at least for me it's a really handy behavior.

While I agree short ids are somewhat better than actual uuids, I don't really see it as a goal. It's not such a big difference, they are still ids: they are still non-understandable stuff by humans, cumbersome to remember or find in the browser history. We could argue they "feel" better when we copy the url to share (I guess). The one thing it actually fixes is if I need to write the URL by hand in my browser bar, a thing that happens more than we think (I get the invite link on my mobile chat but I want to join on my laptop for example). But custom room names would fix this even more.

**Comment by lebaudantoine** [comment]
Jitsi offers both, custom name and automatically random generated name for rooms (based on what I've read in their doc)

My point was not discarding custom name vs randomly generated ones. We'll support custom name rooms, they're super useful.

If you want to create a meeting on the fly, or for a single occasion, clicking on a button and having a short URL to share is quite cool.

The other issue it solved, is a long URL won't fit easily in the "invitation" pop in. Making them shorter help.

We're a bit biased, I am pretty sure outside of the tech world people don't have much "daily" or recurrent meeting as we do.
